/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.raven.form;

import DomainModel.ChiTietSanPham;
import Service.ChiTietService;
import ServiceImpl.ChiTietServiceImpl;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author FPTSHOP
 */
public class SanPhamDetail extends javax.swing.JFrame {

    private DefaultTableModel defaultTableModel;
    private ChiTietService chiTietService = new ChiTietServiceImpl();
    private ArrayList<ChiTietSanPham> chiTietSanPhams = new ArrayList<>();

    public SanPhamDetail() {
        initComponents();
//        tblChiTiet.setBackground(Color.WHITE);
    }

    public void setTenSP(String tenSP) {
        lblTenSP.setText(tenSP);
        detail(tenSP);
    }

    private void detail(String ten) {
        chiTietSanPhams.clear();
        ArrayList<ChiTietSanPham> listCTSP = chiTietService.searchByTen(ten);
        loadData(listCTSP);
    }

    private void loadData(ArrayList<ChiTietSanPham> list) {
        int i = 1;
        defaultTableModel = (DefaultTableModel) tblChiTiet.getModel();
        defaultTableModel.setRowCount(0);
        for (ChiTietSanPham x : list) {
            if (x.getSanPham().getTen().equals(lblTenSP.getText())) {
                defaultTableModel.addRow(new Object[]{
                    i++,
                    "CTSP" + x.getId(),
                    x.getSanPham().getTen(),
                    x.getHang().getTen(),
                    x.getMauSac().getTen(),
                    x.getChatLieu().getTen(),
                    x.getSize().getTen(),
                    x.getDangAo().getTen(),
                    x.getCoAo().getTen(),
                    x.getCoTay().getTen(),
                    x.getGia(),
                    x.getSoLuong(),
                    x.trangThai()
                });
            }
        }
    }
    private ArrayList<ChiTietSanPham> searchByTrangThai(String trangThai){
        ArrayList<ChiTietSanPham> resultList = new ArrayList<>();
        for(ChiTietSanPham chiTiet : chiTietSanPhams){
            String chiTietTrangThai = chiTiet.trangThai().toLowerCase();
            if(chiTietTrangThai.contains(trangThai.toLowerCase())){
                resultList.add(chiTiet);
            }
        }
        return resultList;
    }

//    private void filter(String query) {
//        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(defaultTableModel);
//        tblChiTiet.setRowSorter(tr);
//        tr.setRowFilter(RowFilter.regexFilter(query, 2));
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblChiTiet = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblTenSP = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cboSearch = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tblChiTiet.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblChiTiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã CTSP", "Tên sản phẩm", "Hãng", "Màu sắc", "Chất liệu", "Size", "Dáng áo", "Cổ áo", "Cổ tay", "Giá", "Số lượng tồn", "Trạng thái"
            }
        ));
        jScrollPane1.setViewportView(tblChiTiet);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Tìm kiếm");

        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Chi tiết sản phẩm: ");

        lblTenSP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cboSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "------***------", "Hãng", "Màu sắc", "Chất liệu", "Size", "Dáng áo", "Cổ áo", "Cổ tay", "Trạng thái" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(cboSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 856, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addComponent(jButton1))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 897, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 507, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        String selected = cboSearch.getSelectedItem().toString();
        if (selected.equals("Chất liệu")) {
            chiTietSanPhams.clear();
            String strFind = "";
            strFind = txtSearch.getText();
            ArrayList<ChiTietSanPham> listSearch = chiTietService.searchByChatLieu(strFind);
            loadData(listSearch);
        } else if (selected.equals("Hãng")) {
            chiTietSanPhams.clear();
            String strFind = "";
            strFind = txtSearch.getText();
            ArrayList<ChiTietSanPham> listSearch = chiTietService.searchByHang(strFind);
            loadData(listSearch);
        } else if (selected.equals("Dáng áo")) {
            chiTietSanPhams.clear();
            String strFind = "";
            strFind = txtSearch.getText();
            ArrayList<ChiTietSanPham> listSearch = chiTietService.searchByDangAo(strFind);
            loadData(listSearch);
        } else if (selected.equals("Màu sắc")) {
            chiTietSanPhams.clear();
            String strFind = "";
            strFind = txtSearch.getText();
            ArrayList<ChiTietSanPham> listSearch = chiTietService.searchByMauSac(strFind);
            loadData(listSearch);
        } else if (selected.equals("Cổ tay")) {
            chiTietSanPhams.clear();
            String strFind = "";
            strFind = txtSearch.getText();
            ArrayList<ChiTietSanPham> listSearch = chiTietService.searchByCoTay(strFind);
            loadData(listSearch);
        } else if (selected.equals("Cổ áo")) {
            chiTietSanPhams.clear();
            String strFind = "";
            strFind = txtSearch.getText();
            ArrayList<ChiTietSanPham> listSearch = chiTietService.searchByCoAo(strFind);
            loadData(listSearch);
        } else if (selected.equals("Size")) {
            chiTietSanPhams.clear();
            String strFind = "";
            strFind = txtSearch.getText();
            ArrayList<ChiTietSanPham> listSearch = chiTietService.searchBySize(strFind);
            loadData(listSearch);
        } else if (selected.equals("Trạng thái")) {
            chiTietSanPhams.clear();
            String strFind = "";
            ArrayList<ChiTietSanPham> listSearch = searchByTrangThai(strFind);
            loadData(listSearch);
        }

    }//GEN-LAST:event_txtSearchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SanPhamDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SanPhamDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SanPhamDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SanPhamDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SanPhamDetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblTenSP;
    public javax.swing.JTable tblChiTiet;
    public javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
